### ISSUE TITLE
Change time format to ISO 8601

### ISSUE THREAD

**Issue by Bitbored** [aperturescience/SnailTime#6]
A time format of `YYYY-MM-DD HH:mm:ss` isn't great imho. It results in spaces in the request URL, which looks weird when they get URL encoded and might cause problems when they are not. Also, when there are standards you can follow, methinks you should follow them.

I suggest to use the ISO 8601 format, e.g `YYYY-MM-DDThh:mm:ss`. This is a widely supported standard that is [suggested by W3C](http://www.w3.org/TR/NOTE-datetime). I would also suggest to support time zones in the request, instead of [forcing the timezone to be UTC+2 ](../blob/master/utils/datetime.js). Defaulting to UTC+2 might be ok, since the API will mostly be used in Belgium anyway.

**Comment by MichielDeMey** [comment]
All dates returned by the API should be formatted according to ISO 8601.
Is there a route that returns a wrongly formatted date?

If you are talking about the `/routes` endpoint, any valid date format that can be parsed by http://momentjs.com/ is accepted.

**Comment by Bitbored** [comment]
I was indeed talking about the `/routes` endpoint, sorry I didn't make this
clear... Lunch time is limited :)

I didn't test if passing a ISO 8601 string works *pokerface*, but by
looking at the code this would surprise me (I only see string being juggled
around). If it does, maybe it's a good idea to use this in the example at
the bottom of the README? I really don't like url's with spaces...

Also, I think the timezone thing could be handled more graceful.

2015-01-05 14:44 GMT+01:00 Michiel De Mey <notifications@github.com>:

**Comment by gillesdemey** [comment]
Confirmed to be a bug.

The datetime is missing the input parameter and is being formatted before we're actually determining the arrival/departure time.

https://github.com/aperturescience/SnailTime/blob/master/routes/routes.js#L21

**Comment by MichielDeMey** [comment]
As a side-note, I believe we should address the timezone issue in a separate Github issue.
Furthermore, I'll add a note to the README regarding to date parsing.
