### ISSUE TITLE
Timezones

### ISSUE THREAD

**Issue by gillesdemey** [aperturescience/SnailTime#7]
We're currently locking the timezone to UTC+2.

Any reason why we shouldn't convert all incoming datetimes to this timezone?

AFAIK the NMBS trains only commute in this particular timezone.

**Comment by Bitbored** [comment]
Right now we assume the API consumer will give us a time in UTC+2. This makes sense if you expect the consumers to only be people from Belgium with an app/browser set on the correct local time. 

However, it could also be that the consumer is actually a server that is located outside of Belgium or for some other reason has a different timezone.

I think It would be best to let the consumer specify the timezone, and maybe default to UTC+2 if no timezone is supplied.

**Comment by MichielDeMey** [comment]
Agreed, let's not lock the timezone.
However this is not considered a high-priority item, so we'll add a note to the README about the current state of dates and timezones.

**Comment by gillesdemey** [comment]
Any request that is made should always be converted to the UTC+2 timezone, since that's where the trains will departure and arrive.

Every response also has the Belgian timezone embedded.

As such, anyone who consumes our API should have the correct relative time (departs in x hours) depending on what timezone you're in and enough information regarding the actual departure and in what timezone.

Since we're dealing with actual transportation in a certain region, we can't return timezone-agnostic information.
