### ISSUE TITLE
End of railtime

### ISSUE THREAD

**Issue by jimbauwens** [aperturescience/SnailTime#8]
Hi,

Just posting here to say that the Railtime domain now redirects to the website of the NMBS/SNCB. The app has stopped working, so I assume that the API endpoints also used by Snailtime don't work anymore.

I hope that the NMBS/SNCB app uses the same or similar API.

Greetings,
Jim

**Comment by jimbauwens** [comment]
The 'new' API is not user friendly at all and I don't think Snailtime as is will ever be able to work with it :(

**Comment by gillesdemey** [comment]
I agree that the new API is more of a downgrade than anything else.

Nonetheless I had fun working on this project and maybe we'll just take a look at their other API as well.

**Comment by MichielDeMey** [comment]
I just checked, the API is still online but it seems like they changed the authentication codes since it's returning 401 Unauthorised on all API calls now.

This leads me to believe that they might still be using this API internally, but have blocked access to the public.

**Comment by jimbauwens** [comment]
Ah, interesting.

Regarding the Hafas API used by the NMBS/SNCB app, there has been already some work done. For example: https://groups.google.com/forum/#!topic/public-transport-enabler-discuss/m-FmIS8DJSo .

**Comment by MichielDeMey** [comment]
The guys at iRail have also done a nice job on the NMBS API:
https://github.com/iRail/iRail/tree/master/api/data/NMBS.

**Comment by jimbauwens** [comment]
Hmm, also interesting. I tried BeRails a bit earlier and it didn't work, so I thought that they were using the RailTime API. Probably it was just some other issue.

**Comment by gillesdemey** [comment]
AFAIK iRail is very different in that they scrape content and add it to a db instead of functioning as a proxy for a different API.
